version: "2"

linters:
  enable:
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - errcheck
    - unconvert
    - unparam
    - errorlint

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
  exclude-files:
    - "*_test.go"
